# Configuration file for importing selected OSM quality layers into OGR
[general]

closed_ways_are_polygons=aeroway,amenity,boundary,building,craft,geological,historic,landuse,leisure,military,natural,office,place,shop,sport,tourism,highway=platform,public_transport=platform
tags_format=json

[points]
osm_id=yes
attributes=name,name:de,amenity,shop,leisure,landuse,natural,man_made,highway,other_tags
ignore=created_by,converted_by,source,time,ele,note,todo,openGeoDB:,fixme,FIXME

[lines]
osm_id=yes
attributes=name,highway,man_made,other_tags
ignore=created_by,converted_by,source,time,ele,note,todo,openGeoDB:,fixme,FIXME

[multipolygons]
osm_id=yes
attributes=name,name:de,amenity,shop,leisure,landuse,natural,man_made,highway,other_tags,type
ignore=area,created_by,converted_by,source,time,ele,note,todo,openGeoDB:,fixme,FIXME

[multilinestrings]
osm_id=yes
attributes=name,man_made,highway,other_tags,type
ignore=area,created_by,converted_by,source,time,ele,note,todo,openGeoDB:,fixme,FIXME

[other_relations]
osm_id=yes
attributes=name,man_made,highway,other_tags,type
ignore=area,created_by,converted_by,source,time,ele,note,todo,openGeoDB:,fixme,FIXME
