# Configuration file for importing OSM data into OGR
[general]

closed_ways_are_polygons=aeroway,amenity,boundary,building,craft,geological,historic,landuse,leisure,military,natural,office,place,shop,sport,tourism,highway=platform,public_transport=platform
tags_format=json

[points]
osm_id=yes
attributes=name,barrier,highway,ref,address,is_in,place,man_made
unsignificant=created_by,converted_by,source,time,ele,attribution
ignore=created_by,converted_by,source,time,ele,note,todo,openGeoDB:,fixme,FIXME

[lines]
osm_id=yes
attributes=name,highway,waterway,aerialway,barrier,man_made,railway
ignore=created_by,converted_by,source,time,ele,note,todo,openGeoDB:,fixme,FIXME
computed_attributes=z_order
z_order_type=Integer
z_order_sql="SELECT (CASE [highway] WHEN 'minor' THEN 3 WHEN 'road' THEN 3 WHEN 'unclassified' THEN 3 WHEN 'residential' THEN 3 WHEN 'tertiary_link' THEN 4 WHEN 'tertiary' THEN 4 WHEN 'secondary_link' THEN 6 WHEN 'secondary' THEN 6 WHEN 'primary_link' THEN 7 WHEN 'primary' THEN 7 WHEN 'trunk_link' THEN 8 WHEN 'trunk' THEN 8 WHEN 'motorway_link' THEN 9 WHEN 'motorway' THEN 9 ELSE 0 END) + (CASE WHEN [bridge] IN ('yes', 'true', '1') THEN 10 ELSE 0 END) + (CASE WHEN [tunnel] IN ('yes', 'true', '1') THEN -10 ELSE 0 END) + (CASE WHEN [railway] IS NOT NULL THEN 5 ELSE 0 END) + (CASE WHEN [layer] IS NOT NULL THEN 10 * CAST([layer] AS INTEGER) ELSE 0 END)"

[multipolygons]
osm_id=yes
attributes=name,name:de,type,admin_level,boundary,place,ref,population,wikipedia,wikidata,de:amtlicher_gemeindeschluessel
ignore=area,created_by,converted_by,source,time,ele,note,todo,openGeoDB:,fixme,FIXME

[multilinestrings]
osm_id=yes
attributes=name,type
ignore=area,created_by,converted_by,source,time,ele,note,todo,openGeoDB:,fixme,FIXME

[other_relations]
osm_id=yes
attributes=name,type
ignore=area,created_by,converted_by,source,time,ele,note,todo,openGeoDB:,fixme,FIXME
